### ISSUE TITLE
Version mismatch?

### ISSUE THREAD

**Issue by stevee02** [reversegear/scrcpy-pi-omx#1]
Hi there. I am new to github so please excuse my lack of knowledge. I built the latest version of scrcpy (v1.14) on my Pi Zero and am trying to run your script but I get the following error. Any ideas? 
`pi@raspberrypi:~/scrcpy/scrcpy-pi-omx $ ./startscreen.sh
List of devices attached
192.168.0.14:5555	device

/usr/local/share/scrcpy/scrcpy-server:...shed. 1.3 MB/s (33142 bytes in 0.025s)
mkfifo: cannot create fifo '/home/pi/streamer': File exists
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (1.14) does not match the client (0)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:119)
	at com.genymobile.scrcpy.Server.main(Server.java:221)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)`

**Comment by PeterNjeim** [comment]
Exact same error. It's driven me crazy for the past 2 months. The only way I can get rpi3 working decently with scrcpy is to use `sudo raspi-config` and enable one of the two GL drivers in the advanced settings. I can run at a smooth 60fps with about 10ms latency if I limit the resolution to 480p or less. Of course this isn't ideal and that's why I want this omx version to work, but can't quite surpass this problem.

**Comment by PeterNjeim** [comment]
Well, scrcpy got a huge update today (1.15.1) and so the rpi3 can run at 768x432 60fps flawlessly with the fake kms GL Driver enabled. Which means it looks good enough and so I don't need this project anymore.

**Comment by mattlacey** [comment]
FWIW even after reading @PeterNjeim's comment I still didn't twig immediately and it took me a fair bit of mucking around before I re-read it and paid attention to the fake kms GL Driver part... On the off chance that I could save others time I wrote up all the steps I undertook on a 3b: https://mattlacey.com/posts/2021-04-01-casting-android-to-raspberry-pi/
